"""Add normalized_name column to issuers

Revision ID: 0b6d840dde1a
Revises: a3a0d2b508f9
Create Date: 2026-05-06 20:51:26.468133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6d840dde1a'
down_revision: Union[str, Sequence[str], None] = 'a3a0d2b508f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable so existing rows (if any) don't violate NOT NULL.
    op.add_column('issuers', sa.Column('normalized_name', sa.String(), nullable=True))

    # Step 2: Backfill any existing rows. Uses upper(trim(name)) which matches
    # Issuer.normalize_name for any name that has already been through
    # Issuer.__post_init__ (which strips and collapses internal whitespace).
    op.execute("UPDATE issuers SET normalized_name = upper(trim(name))")

    # Step 3: Alter the column to NOT NULL. SQLite requires recreating the
    # table for this, which batch_alter_table handles transparently.
    with op.batch_alter_table('issuers') as batch_op:
        batch_op.alter_column('normalized_name', nullable=False)

    # Step 4: Add the unique index for fast lookup.
    op.create_index(
        op.f('ix_issuers_normalized_name'),
        'issuers',
        ['normalized_name'],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issuers_normalized_name'), table_name='issuers')
    op.drop_column('issuers', 'normalized_name')
    # ### end Alembic commands ###
