"""add curation_memory table

Revision ID: 8010f6133718
Revises: 0b6d840dde1a
Create Date: 2026-05-13 21:53:31.667954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8010f6133718'
down_revision: Union[str, Sequence[str], None] = '0b6d840dde1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curation_memory',
    sa.Column('normalized_issuer_name', sa.String(), nullable=False),
    sa.Column('conglomerate', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('normalized_issuer_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curation_memory')
    # ### end Alembic commands ###
