"""initial schema with issuers and investments

Revision ID: a3a0d2b508f9
Revises: 
Create Date: 2026-05-04 19:34:26.248311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a0d2b508f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('conglomerate', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('principal_currency', sa.String(), nullable=False),
    sa.Column('rate_kind', sa.String(), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('coupon_frequency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    op.drop_table('issuers')
    # ### end Alembic commands ###
